services:
  # Infrastructure
  nats:
    container_name: nats
    image: nats:2.10
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-c", "/etc/nats/nats.conf"]
    volumes:
      - ./internal/nats_client/nats.conf:/etc/nats/nats.conf
      - nats-data:/data
    restart: unless-stopped
  
  # Microservices
  file-upload:
    container_name: file-upload
    build: 
      context: .
      dockerfile: ./services/file-upload/Dockerfile
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - PORT=8010
    ports:
      - "8010:8010"

volumes:
  nats-data:
